# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Manipulation defaults shared by saved-script skills."""

GRIPPER_WIDTH_M = 0.08
GRIP_TIGHT_M = 0.005
HOVER_CLEARANCE_M = 0.15
HOVER_CLEARANCE_CANDIDATES_M = (0.10, 0.15, 0.20, 0.25)
LIFT_HEIGHT_M = 0.10
J6_SPEED_DEG_S = 50.0
J6_LIMIT_RAD = 2.094
KEYPOINT_SPACING_DEG = 1.0

MAX_GRASP_ATTEMPTS = 5
MAX_NO_PROGRESS_ROUNDS = 3

TWO_D_TOP_DOWN_Z_M = 0.79
